begin;

insert into silniki (typ, pojemnosc, moc, moment) values ('benzynowy', 1200, 85, 160);
insert into silniki (typ, pojemnosc, moc, moment) values ('benzynowy', 1200, 105, 175);
insert into silniki (typ, pojemnosc, moc, moment) values ('benzynowy', 1400, 140, 220);
insert into silniki (typ, pojemnosc, moc, moment) values ('benzynowy', 2000, 300, 380);
insert into silniki (typ, pojemnosc, moc, moment) values ('wysokoprezny', 1600, 105, 250);
insert into silniki (typ, pojemnosc, moc, moment) values ('wysokoprezny', 2000, 150, 320);
insert into silniki (typ, pojemnosc, moc, moment) values ('benzynowy', 1400, 160, 240);
insert into silniki (typ, pojemnosc, moc, moment) values ('benzynowy', 2000, 210, 280);

insert into placowki (nazwa, adres, telefon, mail) values('Volkswagen Krupowki', 'Kwiatowa 15 Zakopane', '976-451-756', 'vwk@poczta.pl');
insert into placowki (nazwa, adres, telefon, mail) values('Volkswagen Warszawa', 'Radzyminska 78 Warszawa', '653-492-603', 'vwwar@poczta.pl');
insert into placowki (nazwa, adres, telefon, mail) values('Volkswagen Slask', 'Fabryczna 12 Katowice', '593-563-552', 'slaskvw@poczta.pl');

insert into nadwozia (typ, liczba_drzwi) values('hatchback', 3);
insert into nadwozia (typ, liczba_drzwi) values('hatchback', 5);
insert into nadwozia (typ, liczba_drzwi) values('sedan', 4);
insert into nadwozia (typ, liczba_drzwi) values('kombi', 5);
insert into nadwozia (typ, liczba_drzwi) values('liftback', 5);
insert into nadwozia (typ, liczba_drzwi) values('suv', 5);
insert into nadwozia (typ, liczba_drzwi) values('suv', 3);
insert into nadwozia (typ, liczba_drzwi) values('van', 3);
insert into nadwozia (typ, liczba_drzwi) values('fastback', 2);
insert into nadwozia (typ, liczba_drzwi) values('coupe', 2);
insert into nadwozia (typ, liczba_drzwi) values('kabriolet', 2);
insert into nadwozia (typ, liczba_drzwi) values('kabriolet', 4);
insert into nadwozia (typ, liczba_drzwi) values('roadster', 2);

insert into modele (producent, nazwa, produkowany_od, gwarancja) values('Volkswagen', 'Golf', '2008-01-01', 3);
insert into modele (producent, nazwa, produkowany_od, gwarancja) values('Volkswagen', 'Passat', '2009-01-01', 3);

insert into kolory_view values('metaliczny', 'czerwony');
insert into kolory_view values('metaliczny', 'czarny');
insert into kolory_view values('metaliczny', 'niebieski');
insert into kolory_view values('metaliczny', 'zielony');
insert into kolory_view values('metaliczny', 'szary');
insert into kolory_view values('perlowy', 'bialy');
insert into kolory_view values('perlowy', 'czarny');
insert into kolory_view values('matowy', 'czarny');

insert into wersje_view values(DEFAULT, 'Volkswagen', 'Golf', 'Trendline', 'benzynowy', 1200, 85, 160, 'hatchback', 3, 'metaliczny', 61790);
insert into wersje_view values(DEFAULT, 'Volkswagen', 'Golf', 'Trendline', 'benzynowy', 1200, 105, 175, 'hatchback', 3, 'metaliczny', 65990);
insert into wersje_view values(DEFAULT, 'Volkswagen', 'Golf', 'Trendline', 'benzynowy', 1200, 85, 160, 'hatchback', 5, 'metaliczny', 62990);
insert into wersje_view values(DEFAULT, 'Volkswagen', 'Golf', 'Highline', 'benzynowy', 1400, 122, 200, 'hatchback', 5, 'metaliczny', 78090);
insert into wersje_view values(DEFAULT, 'Volkswagen', 'Golf', 'Trendline', 'benzynowy', 1200, 105, 175, 'hatchback', 5, 'metaliczny', 67190);
insert into wersje_view values(DEFAULT, 'Volkswagen', 'Golf', 'Trendline', 'wysokoprezny', 1600, 105, 250, 'hatchback', 5, 'metaliczny', 77290);
insert into wersje_view values(DEFAULT, 'Volkswagen', 'Golf', 'Highline', 'benzynowy', 1400, 140, 220, 'hatchback', 5, 'metaliczny', 81290);
insert into wersje_view values(DEFAULT, 'Volkswagen', 'Golf', 'Highline', 'wysokoprezny', 2000, 150, 320, 'hatchback', 5, 'metaliczny', 95190);
insert into wersje_view values(DEFAULT, 'Volkswagen', 'Golf', 'R', 'benzynowy', 2000, 300, 380, 'hatchback', 5, 'metaliczny', 149190);
insert into wersje_view values(DEFAULT, 'Volkswagen', 'Passat', 'Highline', 'benzynowy', 1400, 160, 240, 'sedan', 4, 'metaliczny', 110690);
insert into wersje_view values(DEFAULT, 'Volkswagen', 'Passat', 'Highline', 'benzynowy', 2000, 210, 280, 'kombi', 5, 'metaliczny', 138590);

insert into wyposazenia (id_wersji, nazwa, cena) values(1, 'abs', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(2, 'abs', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(3, 'abs', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(4, 'abs', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(5, 'abs', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(6, 'abs', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(7, 'abs', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(8, 'abs', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(9, 'abs', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(10, 'abs', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(11, 'abs', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(1, 'esp', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(2, 'esp', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(3, 'esp', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(4, 'esp', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(5, 'esp', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(6, 'esp', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(7, 'esp', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(8, 'esp', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(9, 'esp', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(10, 'esp', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(11, 'esp', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(1, 'centralny zamek', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(2, 'centralny zamek', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(3, 'centralny zamek', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(4, 'centralny zamek', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(5, 'centralny zamek', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(6, 'centralny zamek', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(7, 'centralny zamek', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(8, 'centralny zamek', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(9, 'centralny zamek', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(10, 'centralny zamek', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(11, 'centralny zamek', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(1, 'klimatyzacja man', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(2, 'klimatyzacja man', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(3, 'klimatyzacja man', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(4, 'klimatyzacja man', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(5, 'klimatyzacja man', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(6, 'klimatyzacja man', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(7, 'klimatyzacja aut', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(8, 'klimatyzacja aut', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(9, 'klimatyzacja aut', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(10, 'klimatyzacja aut', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(11, 'klimatyzacja aut', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(1, 'alarm', 750);
insert into wyposazenia (id_wersji, nazwa, cena) values(2, 'alarm', 750);
insert into wyposazenia (id_wersji, nazwa, cena) values(3, 'alarm', 750);
insert into wyposazenia (id_wersji, nazwa, cena) values(4, 'alarm', 750);
insert into wyposazenia (id_wersji, nazwa, cena) values(5, 'alarm', 750);
insert into wyposazenia (id_wersji, nazwa, cena) values(6, 'alarm', 750);
insert into wyposazenia (id_wersji, nazwa, cena) values(7, 'alarm', 750);
insert into wyposazenia (id_wersji, nazwa, cena) values(8, 'alarm', 750);
insert into wyposazenia (id_wersji, nazwa, cena) values(9, 'alarm', 750);
insert into wyposazenia (id_wersji, nazwa, cena) values(10, 'alarm', 1790);
insert into wyposazenia (id_wersji, nazwa, cena) values(11, 'alarm', 1790);
insert into wyposazenia (id_wersji, nazwa, cena) values(7, 'tempomat', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(8, 'tempomat', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(9, 'tempomat', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(10, 'tempomat', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(11, 'tempomat', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(1, 'alufelgi', 1030);
insert into wyposazenia (id_wersji, nazwa, cena) values(2, 'alufelgi', 1030);
insert into wyposazenia (id_wersji, nazwa, cena) values(3, 'alufelgi', 1030);
insert into wyposazenia (id_wersji, nazwa, cena) values(4, 'alufelgi', 1030);
insert into wyposazenia (id_wersji, nazwa, cena) values(5, 'alufelgi', 1030);
insert into wyposazenia (id_wersji, nazwa, cena) values(6, 'alufelgi', 1030);
insert into wyposazenia (id_wersji, nazwa, cena) values(7, 'alufelgi', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(8, 'alufelgi', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(9, 'alufelgi', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(10, 'alufelgi', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(11, 'alufelgi', 0);
insert into wyposazenia (id_wersji, nazwa, cena) values(10, 'czujniki parkowania', 2100);
insert into wyposazenia (id_wersji, nazwa, cena) values(11, 'czujniki parkowania', 2100);

insert into klienci (nazwa, telefon, mail, adres) values('Doge', '696-569-769', 'MuchWow@Mail.org', 'SuchStreet 6');
insert into klienci (nazwa, telefon) values('Jas Roztocze', '911-112-765');
insert into klienci (nazwa, telefon, adres) values('Zomfg Enterprises', '555-419-555', 'Soft Street 18');

insert into auta_na_sprzedaz values('ye93vn3jo', '2014-01-11', 0, 1, 1, 1);
insert into auta_na_sprzedaz values('jfd98q2js', '2013-12-06', 0, 5, 1, 3);
insert into auta_na_sprzedaz values('dsv3wb3bs', '2013-12-10', 0, 5, 1, 5);
insert into auta_na_sprzedaz values('jytbd3356', '2014-01-10', 0, 8, 1, 3);
insert into auta_na_sprzedaz values('593mvdskf', '2014-01-01', 0, 9, 2, 3);
insert into auta_na_sprzedaz values('kwien24vn', '2014-01-02', 0, 2, 2, 4);
insert into auta_na_sprzedaz values('alfdneow2', '2014-01-03', 0, 7, 3, 2);
insert into auta_na_sprzedaz values('vvye5n3ma', '2014-01-08', 0, 8, 3, 1);
insert into auta_na_sprzedaz values('wm38vnas9', '2013-12-16', 0, 3, 3, 2);
insert into auta_na_sprzedaz values('nv923mfks', '2014-01-12', 0, 10, 2, 2);
insert into auta_na_sprzedaz values('sfowiv392', '2014-01-13', 0, 11, 3, 3);

insert into auta_klientow values('g45h4h98h', 'KRA 3451', '2009-05-12', 123500, 3, '2009-12-18', 62990, 1, 2, 1);
insert into auta_klientow values('gb32brdnr', 'KN 28456', '2011-03-18', 58700, 9, '2011-06-10', 149940, 1, 1, 2);
insert into auta_klientow values('moe8cn2ks', 'WW 1K384', '2010-11-08', 96000, 8, '2010-11-30', 95940, 2, 3, 4);
insert into auta_klientow values('wwv38bmnd', 'SK 39123', '2012-02-25', 23500, 5, '2012-03-19', 68970, 3, 3, 3);

insert into konfiguracje (vin, nazwa) values('jfd98q2js', 'alarm');
insert into konfiguracje (vin, nazwa) values('dsv3wb3bs', 'alufelgi');
insert into konfiguracje (vin, nazwa) values('wm38vnas9', 'alufelgi');
insert into konfiguracje (vin, nazwa) values('nv923mfks', 'alarm');
insert into konfiguracje (vin, nazwa) values('sfowiv392', 'czujniki parkowania');

insert into konfiguracje (vin, nazwa) values('gb32brdnr', 'alarm');
insert into konfiguracje (vin, nazwa) values('moe8cn2ks', 'alarm');
insert into konfiguracje (vin, nazwa) values('wwv38bmnd', 'alarm');
insert into konfiguracje (vin, nazwa) values('wwv38bmnd', 'alufelgi');

insert into naprawy (vin, placowka, data, koszt, opis) values('g45h4h98h', 1, '2010-01-21', 800, 'Wymiana prawego lusterka.');
insert into naprawy (vin, placowka, data, koszt, opis) values('moe8cn2ks', 2, '2012-07-17', 2000, 'Lakierowanie przedniego zderzaka.');

commit;
